# Generated by Django 4.1 on 2022-08-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                ("commented_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                ("posted_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("profile_pic", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="React",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "react",
                    models.CharField(
                        choices=[
                            ("WOW", "WOW"),
                            ("LIT", "WOW"),
                            ("LOVE", "LOVE"),
                            ("HA", "HAHA"),
                            ("UP", "THUMBS - UP"),
                            ("DOWN", "THUMBS - DOWN"),
                            ("ANGRY", "ANGRY"),
                            ("SAD", "SAD"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reaction", models.CharField(max_length=100)),
                ("reacted_at", models.DateTimeField()),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fb_post.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fb_post.post"
                    ),
                ),
                (
                    "reacted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fb_post.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="posted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fb_post.user"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="commented_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fb_post.user"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fb_post.post"
            ),
        ),
    ]
